[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Adwaita-Xfce U
Comment=Adwaita GTK theme forked from upstream, Designed and Optimized for Xfce (Universal version).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Adwaita-Xfce U
Type=X-GNOME-Metatheme
Comment=Adwaita GTK theme forked from upstream, Designed and Optimized for Xfce (Universal version).
Encoding=UTF-8
GtkTheme=Adwaita-Xfce U
MetacityTheme=Adwaita
IconTheme=Adwaita
CursorTheme=Adwaita
CursorSize=24
ButtonLayout=:minimize,maximize,close
